name: Portfolio 2019 Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_2019 }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_2019 }}
on: workflow_dispatch

jobs:
  Deploy-Production:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Change working directory
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7.22.0
          run_install: false
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.1
          cache: "pnpm"
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Dependency
        run: pnpm install
      - name: Install Vercel CLI
        run: pnpm i -g vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN_PORTFOLIO_ALL }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN_PORTFOLIO_ALL }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN_PORTFOLIO_ALL }}
